modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId          = "digitalandanalogcircuits"
version        = "1.0.0"
displayName    = "Create: Digital and Analog Circuits"
authors = "Cherrylanterns"
description    = '''
机械动力：数字与模拟电路
'''

[[dependencies.digitalandanalogcircuits]]
    modId      = "neoforge"
    type       = "required"
    versionRange = "[21.1,)"
    ordering   = "NONE"
    side       = "BOTH"

[[dependencies.digitalandanalogcircuits]]
    modId      = "minecraft"
    type       = "required"
    versionRange = "[1.21.1,1.22)"
    ordering   = "NONE"
    side       = "BOTH"

# Create dependency – optional for now, required once we use its API
 [[dependencies.digitalandanalogcircuits]]
     modId      = "create"
     type       = "optional"
     versionRange = "[0.5,)"
     ordering   = "AFTER"
     side       = "BOTH"
